version: '3.9'

services:
  database:
    container_name: database
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_VERSION=10.6
    volumes:
      - ${ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - ${DATABASE_LOCALHOST_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/ebanx-tst
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: ./docker/php/
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/ebanx-tst
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8083:80'
    depends_on:
      - database
      - php
      - nginx

volumes:
  mariadb_data:
    driver: local